/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeandroid_jenoa_LibDL */

#ifndef _Included_nativeandroid_jenoa_LibDL
#define _Included_nativeandroid_jenoa_LibDL
#ifdef __cplusplus
extern "C" {
#endif
#undef nativeandroid_jenoa_LibDL_RTLD_LAZY
#define nativeandroid_jenoa_LibDL_RTLD_LAZY 1L
#undef nativeandroid_jenoa_LibDL_RTLD_NOW
#define nativeandroid_jenoa_LibDL_RTLD_NOW 2L
#undef nativeandroid_jenoa_LibDL_RTLD_BINDING_MASK
#define nativeandroid_jenoa_LibDL_RTLD_BINDING_MASK 3L
#undef nativeandroid_jenoa_LibDL_RTLD_NOLOAD
#define nativeandroid_jenoa_LibDL_RTLD_NOLOAD 4L
#undef nativeandroid_jenoa_LibDL_RTLD_DEEPBIND
#define nativeandroid_jenoa_LibDL_RTLD_DEEPBIND 8L
#undef nativeandroid_jenoa_LibDL_RTLD_NODELETE
#define nativeandroid_jenoa_LibDL_RTLD_NODELETE 4096L
/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    init_libdl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeandroid_jenoa_LibDL_init_1libdl
  (JNIEnv *, jclass);

/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    cleanup_libdl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeandroid_jenoa_LibDL_cleanup_1libdl
  (JNIEnv *, jclass);

/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    dlopen
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_nativeandroid_jenoa_LibDL_dlopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    dlerror
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeandroid_jenoa_LibDL_dlerror
  (JNIEnv *, jobject);

/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    dlclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nativeandroid_jenoa_LibDL_dlclose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nativeandroid_jenoa_LibDL
 * Method:    dlsym
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nativeandroid_jenoa_LibDL_dlsym
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
